### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by xQsme** [gboudreau/XBMCnfoTVImporter.bundle#121]
I updated plex to the new media agent recently, today I remembered trying to fix my shows that are using this plugin, but I'm not able to, it seems it's not picking up any of my local data, I even tried moving local data to the top of the agent priorities to no avail.

Anyone can offer some assistance? Thanks

**Comment by randallbruder** [comment]
You can't use the new Plex TV Series agent without the entire library also using that agent. Meaning any show that was using XBMCnfoTVImporter as an agent got switched to the new Plex TV Series agent. There's no way to override a single show in an upgraded library.
