### ISSUE TITLE
Feature Request: add unique episode id

### ISSUE THREAD

**Issue by arabcoders** [gboudreau/XBMCnfoTVImporter.bundle#123]
Hi, 

Thank you for you efforts on getting NFO files to work with plex, I have small request if possible, i developed a tool that sync watch state a cross media servers, and cross my testing a user reported problem regarding NFO agents, i managed to fix the movies one as it's really easy and already provides the unique id via `com.plexapp.agents.xbmcnfo://(id)?lang=xn`. 

However the the tv nfo agent does not provider the needed information, it provides the following `com.plexapp.agents.xbmcnfotv://(show-id)/(season)/(episode)?lang=xn` and the tool i developed rely solely on info provided via the media servers. 

So i asked the user, and he said that the NFO files he has providers unique episodes ID so if it's possible to include this information in the GUID i would be grateful. for example it can be `com.plexapp.agents.xbmcnfotv://(show-id)/(season)/(episode)?lang=xn&episode=(id)` 

Thank you.

**Comment by almightiest** [comment]
@ArabCoders I did some digging into this and after debugging I do not see any way to alter the guid of an episode.  The `(show-id)/(season)/(episode)` format is plex's internal model for their older scrapers it seems.  Hopefully this isn't an issue anymore anyways for your project!

**Comment by arabcoders** [comment]
> @ArabCoders I did some digging into this and after debugging I do not see any way to alter the guid of an episode. The `(show-id)/(season)/(episode)` format is plex's internal model for their older scrapers it seems. Hopefully this isn't an issue anymore anyways for your project!

Indeed it's not an issue anymore.
