### ISSUE TITLE
Shows or Episode titles with "&" in them do not get processed.

### ISSUE THREAD

**Issue by bdwilson** [gboudreau/XBMCnfoTVImporter.bundle#31]
I have a show with the tvshow.nfo title with a & in it (<title>Thomas The Tank Engine & Friends</title>).  All the episodes under this do not get processed and show up in Plex.   All I see is "Season 10, Episode 2" and not the title:

Thomas.and.Friends-Fire & Water-S10E02.nfo
::::::::::::::
```xml
<episodedetails xsd="http://www.w3.org/2001/XMLSchema" xsi="http://www.w3.org/2001/XMLSchema-instance">
<title>Fire & Water</title>
</code>
```
Also, the title for this episode is not showing either:

```xml
$ more "You're In Love & It's Your First Kiss Charlie Brown-s00e05.nfo"
<episodedetails xsd="http://www.w3.org/2001/XMLSchema" xsi="http://www.w3.org/2001/XMLSchema-instance">
<title>You're In Love & It's Your First Kiss Charlie Brown</title>
```
I see in the code that you're doing a regex with &'s but for some reason it doesn't appear to be working for me.

Thanks,
Brian

**Comment by SlrG** [comment]
As there were no more reports for problems with &s, I'm closing this issue for now. If you still have problems, please reopen and provide testing samples.
