### ISSUE TITLE
Multi episode files result in video download as thumbnail

### ISSUE THREAD

**Issue by MartinHaimberger** [gboudreau/XBMCnfoTVImporter.bundle#71]
I have for all my media nfo files, some of the video files are named Exx-Eyy if this is a multiple episode file. Now i have the problem, that for the secound episode the video itself is downloaded as thumbnail to the metadata folder.

For now disabling the multi episode file support works for me.

I commented out following lines:

if episodeThumbFilename:
thumbData = Core.storage.load(episodeThumbFilename)
episode.thumbs[episodeThumbFilename] = Proxy.Media(thumbData)
Log('Found episode thumb image at ' + episodeThumbFilename)

**Comment by SlrG** [comment]
Thanks for pointing out this problem. I'll try to replicate and correct it.

**Comment by MartinHaimberger** [comment]
If u need some more information or maybe some nfo files where that happend, i can send it to you.

**Comment by SlrG** [comment]
I can't replicate the problem on my library. So I'll need you to zip up one of the tvshows where this happens. Please leave out the episode media files, but include all additional metadata (nfos, jpgs, ...). Please also add a listing with the filenames of the episode media files.

**Comment by SlrG** [comment]
Do you still have this problem? Please help me reproduce it and provide me with a testing sample as I requested above.

**Comment by SlrG** [comment]
I'm closing this, as I can't replicate it and the poster doesn't respond anymore.
