### ISSUE TITLE
Rating is not imported from XBMC NFO files for TV shows

### ISSUE THREAD

**Issue by AndrewR79** [gboudreau/XBMCnfoTVImporter.bundle#73]
![git1](https://cloud.githubusercontent.com/assets/16125868/11547543/96885ee2-994c-11e5-8982-51ed835e2c00.PNG)
![git2](https://cloud.githubusercontent.com/assets/16125868/11547542/9683dfc0-994c-11e5-84e0-f3f3f70c4038.PNG)

It stopped working around 3 months ago, probably with a PMS update.
It's still working fine for the Movie importer though
Edit: To be clear, I am talking about the individual episode ratings, not the age rating/certificate

**Comment by SlrG** [comment]
Please recheck with the newest version of the agent and report if it is fixed or still happening for you.

**Comment by AndrewR79** [comment]
Brilliant, it appears to be fixed! Thanks a lot
