### ISSUE TITLE
Multiple episodes not importing

### ISSUE THREAD

**Issue by Malathan** [gboudreau/XBMCnfoTVImporter.bundle#74]
If a media file is named "tvshow - s01e01e02e03e04.ext", Plex only see's e01 and e02.  Not sure if this is due to naming convention difference between Plex and Kodi or XBMCnfoTVImporter.

Renaming videos to plex convention, "tvshow - s01e01-e04.ext" resolves this, but not good option for entire library.

**Comment by SlrG** [comment]
It is sadly the only [naming convention](https://support.plex.tv/hc/en-us/articles/200220687-Naming-Series-Season-Based-TV-Shows) that is supported by Plex at the moment and the agent can only assign info to episodes, that are recognized by plex. Why they choose a different approach than Kodi and support only that, I don't know. And what makes matters worse, is that Kodi doesn't support Plex way to do it ([see here](http://kodi.wiki/view/Naming_video_files/TV_shows#Multi-episode)). Only solution is to pester the Plex devs to support Kodi naming and Kodi devs to support Plex'.
