### ISSUE TITLE
problem ascii encode character

### ISSUE THREAD

**Issue by laouache** [gboudreau/XBMCnfoTVImporter.bundle#76]
Hello,

I have some issue using your plug in with special characters.
I activated logs and i have this:
CRITICAL (runtime:298) - Exception in task thread (most recent call last):

File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 84: ordinal not in range(128)

If you want complete logs, i can send you private.

**Comment by SlrG** [comment]
On what system are you using the agents? Fulls logs would be great. Also please zip up the folder of the movie or tv show, where the error happens. Please remove the actual episode or movie file from the zip, but leave in all the other metadata. This will help me pinpoint the problem.

**Comment by Sakujakira** [comment]
Hi there,

it seems like i've got the same error. I've attached you some logs and the metadata.
[com.plexapp.agents.xbmcnfotv.log.txt](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/193709/com.plexapp.agents.xbmcnfotv.log.txt)
[data.tar.gz](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/193701/data.tar.gz)

**Comment by SlrG** [comment]
@Sakujakira: Hmm... Your sample data imports perfectly fine on my system, so I can't really replicate the problem. For me Plex is installed in an ubuntu based docker on my unRAID server. Also the log doesn't give a clear indication what happens and where. I'll try to create a testing version with different logging tomorrow. Please give it a try and report again.

**Comment by SlrG** [comment]
Please give this [testing version](https://github.com/SlrG/XBMCnfoTVImporter.bundle/archive/asciierror.zip) a go.

**Comment by Sakujakira** [comment]
I've tried it.

And this is strange, now it succeed in matching the series, everything is recognized, but i can still see this ascii error in my logs. 
[com.plexapp.agents.xbmcnfotv.log.txt](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/198096/com.plexapp.agents.xbmcnfotv.log.txt)

**Comment by SlrG** [comment]
Not exactly the same error. :) It crashes at another line now. So the checks I added removed the first problem. I'll try to fix the new location, too. I would be kind if you could check that again, so we can remove the problems step by step.

**Comment by SlrG** [comment]
Please give this new [testing version](https://github.com/SlrG/XBMCnfoTVImporter.bundle/archive/asciierror.zip) a go.

**Comment by Sakujakira** [comment]
Hey,

also this error seems gone with your new testing release. 

I've added some Logs, now with no errors at all. So i think this error is now fixed. If you may see some further problem i could also try another testing build.

Thank you for your support.

[com.plexapp.agents.xbmcnfotv.log.txt](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/200762/com.plexapp.agents.xbmcnfotv.log.txt)

**Comment by SlrG** [comment]
That log looks fine indeed. :) I'll merge the changes to the main branch and would like you to test again with that. If everything works as expected, we can close the issue. I have to thank you, for helping me solve the issue. :)

**Comment by Sakujakira** [comment]
Hi,

i'm pretty short on time this week, maybe i've got a little time on this weekend.

**Comment by SlrG** [comment]
No problem. :) I often have the same problem. Take your time.
