### ISSUE TITLE
Episode Thumbnails Not Updating

### ISSUE THREAD

**Issue by fnwc** [gboudreau/XBMCnfoTVImporter.bundle#80]
When using XBMCnfoTVImporter as the agent and changing any of the thumbnails, I can't get Plex to pick up on the thumbnail changes.
1. Add new library
2. Add one show to library, set scraper to XBMCnfoTVImporter
3. Load metadata OK, including correct episode thumbnail
4. Replace episode thumbnail
5. Refresh
6. Old thumbnail still exists
7. I've tried running "Plex Media Scanner.exe" -w -c <section_number> to remove all library data, cleaning bundles, emptying the trash, exiting PMS and then restarting it, refreshing the library (to re-add the data) and nothing works, the old thumb still shows.
8. Changing the library agent to the default Plex TV scanner, "The TVDB" and clicking refresh when the thumbnail changes causes the thumbnail to refresh correctly.

**Comment by SlrG** [comment]
Yes this is a known problem. I have never found a way to force plex to refresh the cached data.
The workaround is to move the complete series to another directory than your library folder. Refresh all, so the series gets removed completely and the move the whole series with modified thumbnail back and refresh all again.

**Comment by Em31Et** [comment]
5. Series Menu "Fix Incorrect Match" > "Auto Match" > "XBMCnfoTVImporter" will be faster

**Comment by fnwc** [comment]
@Em31Et This did not work for me; old thumbnails were still loaded (although I *could* select the new thumbnail in the edit mode).

**Comment by Em31Et** [comment]
did you select thumbnail manually before "Fix Incorrect Match" ?

**Comment by fnwc** [comment]
Yeah I had selected some manually (when I first ran into this problem) on a different episode in the same series. 

Is this a flag in the database I can manually update via SQL?

**Comment by SlrG** [comment]
I wish I would know, what plex's The TVDB agent does differently. I checked the source, but I can't find the reason.

**Comment by AlphaFactory** [comment]
When can this problem be solved?
I am trying to solve this problem, but I totally don't know what's wrong.
It seems no problem in the code.

**Comment by AlphaFactory** [comment]
This problem is already solved since Plex was updated (I don't know the exact version code...)
Anyway, it works again.
I think this issue can be closed.
