### ISSUE TITLE
Season poster not updating

### ISSUE THREAD

**Issue by frostbox** [gboudreau/XBMCnfoTVImporter.bundle#81]
I use this agent to manually handle videos.

If I replace a season in a TV show with new content, the season poster will not be updated.  It will have the previous season poster.

Here are the steps I follow to encounter this.

Create a new TV show with a season.
Assign a season poster and some episodes.  I will refer to the season as Season 1.
Verify that they show up in plex.
Remove the season (I've removed entire season folders or just the contents, it doesn't matter).  Remove the poster associated with Season 1 in the root folder for the TV show.
Update the library and verify that the season has been removed.
Add a new season videos, NFO's and posters into Season 1.  Add the new poster for Season 1 into the root folder for the TV show.
Update the plex libary.
Edit Season 1 in the UI.  It shows the old poster and not the new poster.  At this point, I can add the new poster manually (in the Plex UI) and select it.  It retains the old poster as well.

It's like there is some additional clean up that needs to be performed when removing a season.

**Comment by SlrG** [comment]
@frostbox : temporary removing the whole series and readding it should solve your problem. Sadly plex caches the old poster and I found no way yet to force it to refresh the cache.

**Comment by fnwc** [comment]
I'm having the same problem, just upgraded the plex server where season thumbs were buggy, and now I can't get any season thumbs to show up. Unmatching a TV show causes the season posters to show, then rematching them with XBMCnfoTVImporter causes them to disappear again (using the default show poster).

Is there an easy way to delete a series via Plex command line or something?

**Comment by SlrG** [comment]
Closed, as new issue #89 seems to be fixed.
