### ISSUE TITLE
Memory Leak on Mac OS X /w Plex v1.1.3.2700

### ISSUE THREAD

**Issue by dwhagar** [gboudreau/XBMCnfoTVImporter.bundle#82]
For some reason when the Plex executes the plugin to update metadata from changed .nfo files, the system slogs to a halt.  The plugin quickly gobbles up RAM until the system no longer has enough RAM.  The process remains in this state until killed.

I tried this several times, each time killing the process returned the system to normal within seconds.

**Comment by Em31Et** [comment]
It is a bug for multiple episode file (e.g. S01E01E02.mkv).

```python
if (nfoepc > 1) and (not Prefs['multEpisodePlexPatch'] or not multEpTestPlexPatch):
											for name in glob.glob1(os.path.dirname(nfoFile), '*S' + str(season_num.zfill(2)) + 'E' + str(ep_num.zfill(2)) + '*.*'):
												if "-E" in name: continue
												episodeThumbNames.append (**os.path.join(os.path.dirname(nfoFile), name)**)
```

For multiple episode file, it add  "**S01E01E02.mkv**" as possible thumb file and then load into memory, so all memory gone and hang.

**Comment by dwhagar** [comment]
I’m not familiar with Python 2.x, what might we do to fix this?  I don’t mind making a commit or testing a possible patch myself.
---
David Wade Hagar
david.hagar@gmail.com
http://home.blazingumbra.com/cyclops.html

The freedom of expression protects you from governmental prosecution for something you've said.  It does not, nor has it ever, protected you from potentially harmful reactions of friends, neighbors, or employers, because you've said something stupid.  Doing so would infringe on their freedom of expression.

**Comment by Em31Et** [comment]
seems the code is used for the following case
**S01E01E02.mkv**
**S01E02.jpg** <- to search the separated thumb file for 2nd episode 

Change the following line to load "jpg" file only.

From
```python
for name in glob.glob1(os.path.dirname(nfoFile), '*S' + str(season_num.zfill(2)) + 'E' + str(ep_num.zfill(2)) + '*.*'):
```

To
```python
 # *.* => *.jpg
for name in glob.glob1(os.path.dirname(nfoFile), '*S' + str(season_num.zfill(2)) + 'E' + str(ep_num.zfill(2)) + '*.jpg'):
```

**Comment by dwhagar** [comment]
Sweet, I’ll give that a try.
---
David Wade Hagar
david.hagar@gmail.com
http://home.blazingumbra.com/cyclops.html

The freedom of expression protects you from governmental prosecution for something you've said.  It does not, nor has it ever, protected you from potentially harmful reactions of friends, neighbors, or employers, because you've said something stupid.  Doing so would infringe on their freedom of expression.

**Comment by SlrG** [comment]
Cool. Thanks for reporting and supplying a fix. :) I'll add this to the agents and release a fixed version soon.

**Comment by SlrG** [comment]
@dwhagar : I added @Em31Et s fix to the tv agent. Please give it a try and report if it fixes your problems.

**Comment by SlrG** [comment]
@dwhagar:
Please report back, and close the issue if solved. Thanks. :)

**Comment by SlrG** [comment]
Seems to be resolved.
