### ISSUE TITLE
Episodes not grabbing correct data

### ISSUE THREAD

**Issue by robdennehy** [gboudreau/XBMCnfoTVImporter.bundle#83]
Hi

I have a series where I have manually edited nfo files that were created in Media Companion for Kodi. This has caused the episode numbers to differ from what is on TVDB (though does match TVDB DVD order).

When in Plex, when using this agent, it does not match what is in the nfo and seems to be following the TVDB convention as if drawing episode numbers from the filename and matching from there.

XBMCnfoTVImporter is the library scanner agent, everything else I can turn off is off in the agents settings and I have tried multiple times to match and unmatch, refresh etc. 

Similar is happening on other shows where it simply is showing no information at all.

Could you please let me know where I may be going wrong before I suggest this is a bug?

**Comment by SlrG** [comment]
Hard to tell. Could you zip up the whole series folder without the episode files, but all other metadata and upload it to some sharing service and drop me a link? Using this I can try it on my testing system.

**Comment by robdennehy** [comment]
Hi,

I think I may have attributed the problem elsewhere. I was previously using an older version of your plugin and it must have stopped working at some point. When I updated it it didn't seem to change anything. However while having one more go today before sending you some example metadata I got some traction from the agent.
It seems that Plex's database is "sticky" and when "matching" and "fixing incorrect matches" it seems to keep hold of some problems introduced previously until the computer is restarted. For example after removing a season of a show, refreshing, and then putting it back, I had to restart the machine before it would find the episodes again, despite refreshing.

Sorry to have wasted your time

**Comment by SlrG** [comment]
No problem. :) I'm glad you got it working in the end. I wish I could force plex to ignore all cached data and only use what it fetches new. If anybody knows how, let me know. I'll close your issue for now, as it seems resolved.

**Comment by robdennehy** [comment]
I had some luck when I moved some mis-matched files (They were scanned by plex before I added my metadata) out of my library folder, then wiped the "com.plexapp.agents.xbmcnfotv" cache files in the Plug-in Support folder before moving the files back. This then scanned them properly again without "sticking". Not sure if you as a plug-in author can wipe your own cache but if you can then that might do it.

Hope that's of some help.
