### ISSUE TITLE
support for status-tag?

### ISSUE THREAD

**Issue by angobango** [gboudreau/XBMCnfoTVImporter.bundle#88]
hello,
is there any chance to get support for the status of a tv-show from the .nfo-file (ended / continuing)?
there is no need to automatically update the state or something, but just to grab it from the .nfo-file and put it somewhere in the plex-infos (e.g. before the rating, the summary or whatever), on the tv-show level.

i have some experiences with php, but i'm completely new to python. from the logic of the code i assume this would be somewhat like a snap to put it in, but it probably would take me hours to try by myself and get some decent solution.
would be very nice to see something like a checkbox 'status before summary' or something in the options, or even to choose where it should be added.

i attached a .nfo-file which contains such a status-tag.
[tvshow.txt](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/751773/tvshow.txt)

however, thank you in advance if you decide to add this!

regards

angelo

**Comment by SlrG** [comment]
It should be possible to do. Do you generate this status tag manually or which programs support this? I hesitate to implement things in XBMCnfoImporters, that is not supported by Kodi.

**Comment by angobango** [comment]
hi
the .nfo-file is generated by TinyMediaManager ([http://www.tinymediamanager.org/](http://www.tinymediamanager.org/)). 
in the options there is support for kodi .nfo-files and also for kodi/xbmc < v.16 and media portal. let me know if you need further Information!

**Comment by SlrG** [comment]
It doesn't matter if you have support for kodi enabled in TinyMediaManager. That only meens it will mainly use tags that Kodi supports. But it will still create additional tags, that kodi doesn't support and simply ignores. What does matter is, if the tag is used inside Kodi. Is there a place anywhere, where you see if a tvshow is still airing or not and where that info is exported to this tag by Kodi itself?

**Comment by angobango** [comment]
hi
i can see the tag in the tv-show level:

![status](https://cloud.githubusercontent.com/assets/25539290/22742038/a505a01e-ee15-11e6-928a-f8b3835d771e.jpg)

(not in default-skin Confluence, but for example in Aeon MQ 6)

when i export the library, there is also a status-tag in videodb.xml, for each tv show:
[status.txt](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/760945/status.txt)

not sure whether it's there because it was before, though.
let me know if you need an exported library, which was scraped by the built-in scrapers of kodi and which one it should be.

**Comment by SlrG** [comment]
Thank you for providing this information. I won't need an exported library. Your request for adding this tag to the summary is accepted. I don't know when I'll have the time to add it, but it is on my todo list now and it will be added.

**Comment by angobango** [comment]
great!
thanks a lot!

**Comment by SlrG** [comment]
Sorry, it took me some time. Please give the newest version of the tv agent a go. You need to enable the status tag support in the agents settings. It will be put in front of the summary. Makes no sense IMHO to show it at the end.

**Comment by angobango** [comment]
updating right now, works perfectly!
thanks again, enjoying it! :1st_place_medal:

**Comment by SlrG** [comment]
Cool. :) I'm glad it works and you like it.
