### ISSUE TITLE
Season posters still not showing

### ISSUE THREAD

**Issue by fnwc** [gboudreau/XBMCnfoTVImporter.bundle#89]
Running Plex Version 1.3.4.3285.

I've deleted an entire TV show collection on plex by using the command line: `/path/to/Plex\ Media\ Scanner --reset --section {number}` and then updating the library, but I'm still getting just the generic show poster.

This is how it originally looks, after deleting/resetting the TV show collection and updating. No season posters are visible:
![Initial View](http://i.imgur.com/tB4H6qo.jpg)

After unmatching the show, the season posters are visible:
![Showing Season Poster](http://i.imgur.com/sIAixIm.jpg)

Editing the season shows the poster exists:
![Showing Season Poster](http://i.imgur.com/GA539lD.jpg)

After matching the show again, using XBMCnfoTVImporter:
![Missing Season Poster](http://i.imgur.com/1AdM92A.jpg)

Editing the season shows the poster is missing:
![Missing Season Poster](http://i.imgur.com/yv5cxmx.jpg)

The directory structure:
![Directory Structure](http://i.imgur.com/vHvRbL0.jpg)

Looking at the log file, it seems to have found the image, but it's not showing: `Found season poster file \\persephone\TV Documentaries\Kitchen Nightmares (2007)\season02-poster.jpg`.

The log file is attached.
[xbmcinfotv.txt](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/files/800670/xbmcinfotv.txt)

**Comment by SlrG** [comment]
No error in the logs. So the TVnfoAgent seems to pickup and set the season posters correctly. I had no chance yet to try the new plex version myself. Do you have a plex pass? I'm pretty sure the newest is only available to plex pass members. So it could be you still have an older version.

**Comment by fnwc** [comment]
Well, that worked. Sorry, I read a previous issue and thought by upgrading it would fix it. I didn't realize that Plex Pass (which I have), allows downloads of early clients.

I'm running v1.4.2.3400, which apparently fixes the issue. Thanks.

**Comment by SlrG** [comment]
Cool. I'm glad you got it working. :)

**Comment by diamondsw** [comment]
So am I correct in thinking this error is confirmed in the last public release (1.3.4.3285), but will be fixed whenever the PlexPass release (1.4.2.3400) filters out to the general public?

**Comment by fnwc** [comment]
Seems to be that way, yes. I ended up emptying my collections via command line and simply calling an update again.

**Comment by xjndfdfe** [comment]
Hi
My whole tv collection with multiple season has this problem.
All tv shows will use the same poster for every season.I can manually choose to edit the poster and find the poster file i placed in the Season X folder then replace the default one.
Is there any easy way to solve this?
Sorry but I do not understand the command line way,Thanks!

![1](https://user-images.githubusercontent.com/8081912/80080766-a47c2c80-8584-11ea-937d-a43090e49e0c.jpg)
![2](https://user-images.githubusercontent.com/8081912/80080786-aa720d80-8584-11ea-88bc-1cbe4d9cf0e9.jpg)
![5](https://user-images.githubusercontent.com/8081912/80080792-ac3bd100-8584-11ea-9fc5-57d44a21febc.jpg)
