### ISSUE TITLE
[Patch] Banner and fanart images not used for seasons

### ISSUE THREAD

**Issue by gboudreau** [gboudreau/XBMCnfoTVImporter.bundle#93]
Received this by email. Posting here in case someone wants to integrate this into the codebase.

> Bonjour M. Boudreau,
> 
> J'utilise depuis un certain temps votre projet XBMCnfoTVImporter.bundle et XBMCnfoMoviesImporter.bundle.
> 
> J'ai découvert que dans XBMCnfoTVImporter.bundle les banner et fanart n'étaient pas utilisés pour les saisons des séries.  J'ai donc fait quelques recherches et j'ai finalement fait une version modifiée qui en tient compte.
> 
> J'ai ajouté les lignes qui suivent ma signature à la ligne 614 du fichier __init__.py.  J'ai testé le tout et cela fonctionne très bien.
> 
> Si cela vous intéresse, ne vous gênez pas pour les inclure officiellement dans l'application.
> 
> Merci
> 
> Christian

	# Season Banner
	seasonBannerFileName = 'season%(number)02d-banner.jpg' % {"number": int(season_num)}
	seasonBannerNames = []
	seasonBannerNames.append (os.path.join(seasonPath, seasonBannerFileName))
	seasonBannerNames.append (os.path.join(seasonPath, "banner.jpg"))
	seasonBannerNames.append (os.path.join(seasonPath, "folder-banner.jpg"))
	seasonBannerNames.append (os.path.join(path, seasonBannerFileName))
	seasonBannerNames.append (os.path.join(path, "banner.jpg"))
	seasonBannerNames.append (os.path.join(path, "folder-banner.jpg"))

	# check possible banner file locations
	seasonBanner = self.checkFilePaths (seasonBannerNames, 'season banner')

	if seasonBanner:
		seasonBannerData = Core.storage.load(seasonBanner)
		metadata.seasons[season_num].banners[seasonBanner] = Proxy.Media(seasonBannerData)
		Log('Found season banner image at ' + seasonBanner)

	# Season Fanart
	seasonFanartFileName = 'season%(number)02d-fanart.jpg' % {"number": int(season_num)}
	seasonFanartNames = []
	seasonFanartNames.append (os.path.join(seasonPath, seasonFanartFileName))
	seasonFanartNames.append (os.path.join(path, seasonFanartFileName))
	seasonFanartNames.append (os.path.join(path, "fanart.jpg"))

	# check possible Fanart file locations
	seasonFanart = self.checkFilePaths (seasonFanartNames, 'season fanart')

	if seasonFanart:
		seasonFanartData = Core.storage.load(seasonFanart)
		metadata.seasons[season_num].art[seasonFanart] = Proxy.Media(seasonFanartData)
		Log('Found season fanart image at ' + seasonFanart)

**Comment by SlrG** [comment]
@gboudreau:
Thank you for posting this. I integrated it into the TVImporter. Many thanks for Christian. Your contribution is appreciated.
