### ISSUE TITLE
readme.md hickups

### ISSUE THREAD

**Issue by ukdtom** [gboudreau/XBMCnfoTVImporter.bundle#96]
UAS link is towards the old discontinued UAS

New one is [WebTools](http://forums.plex.tv/discussion/comment/1452792)

/dane22

**Comment by SlrG** [comment]
You are correct. Noticed this yesterday myself. It will be corrected.

**Comment by SlrG** [comment]
Sorry, it took me an awful lot of time.

**Comment by ukdtom** [comment]
No way to reopen here, but have some bad news for you ;)

I created a new thread for WebTools, and this time without a version number in it, so hopefully will last forever

http://forums.plex.tv/discussion/288191

Sorry about that

Tommy
