### ISSUE TITLE
No Episodes Titles

### ISSUE THREAD

**Issue by MuetzeOfficial** [gboudreau/XBMCnfoTVImporter.bundle#99]
Since newest the episodes titles are not taken over any more. There's just episode 1, episode 2, and so on.

Server Debian 9, Plex Version 1.15.5.994 (Beta Channel).

Logs (last 100 lines):
https://docs.google.com/spreadsheets/d/1uy7E9_PbHRBf4zuA1Qim4krHJm9DG6sI1s2k0UrEl30/edit?usp=sharing

Media Scanner Log
https://docs.google.com/spreadsheets/d/1liin1GljwLYOZm5lIrAKMssotySq07cO02r0E1rkMVo/edit?usp=sharing

tvshow.nfo
https://docs.google.com/document/d/17nV37jqJiQyRs3cUDXgY5ago6asOcNdo1wO4XaMyJ8g/edit?usp=sharing

s01e01 - Was sind Webservices.nfo
https://docs.google.com/document/d/1g8OdwjG0MJMJDngu5_A086Cd_3aCHOSOx5_0m7lKnAU/edit?usp=sharing

**Comment by SlrG** [comment]
I stopped using Plex. So I won't work on fixing this problem. Pull requests are welcome.

**Comment by MuetzeOfficial** [comment]
Somehow OMV 4 on Debian 9 seems to consume more resources than OMV 3 on Debian 8.
In any case, I have tested it now, since apart from timeout errors nothing noticeable has been found in the logs and Plex simply gets worse and worse from update to update, one cannot say that it is really due to the script.
At the moment it works, if I let each season read in separately instead of 6 seasons, for example.
So I close this issue and have a look what happened in the next Plex Public Patch.
